# Staging: mismo chart y misma imagen que producción, con menos réplicas.
environment: staging

autoscaling:
  minReplicas: 2
  maxReplicas: 4

nodeSelector:
  kubernetes.io/arch: arm64

githubRepos:
  - londono652/nelua-apii
